/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import java.awt.Image;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Locale;
import javax.persistence.EntityManager;
import javax.persistence.Query;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import vo.Usuario;
import vo.Mensagem;
import persistencia.MensagemDAO;
import persistencia.UsuarioDAO;

/**
 *
 * @author 2info2021
 */
public class TelaLocalizaMensagem extends javax.swing.JFrame {
//icone de erro

    ImageIcon erroIcon = new ImageIcon(this.getClass().getResource("/imagens/erro.png"));
    Image erroImage = erroIcon.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH);
    ImageIcon erroIcon2 = new ImageIcon(erroImage);
    
    EntityManager em;
    Usuario u = new Usuario();
    UsuarioDAO ud = new UsuarioDAO();
    Mensagem m = new Mensagem();
    MensagemDAO md = new MensagemDAO();

    /**
     * Creates new form TelaMensagem
     */
    public TelaLocalizaMensagem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tMensagem = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        tNome = new javax.swing.JLabel();
        bSair = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tFiltro = new javax.swing.JTextField();
        bOk = new javax.swing.JButton();
        tLer = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mNovo = new javax.swing.JMenuItem();
        mExcluir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Home");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        tMensagem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Remetente", "Assunto", "Mensagem", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tMensagem);
        if (tMensagem.getColumnModel().getColumnCount() > 0) {
            tMensagem.getColumnModel().getColumn(0).setResizable(false);
            tMensagem.getColumnModel().getColumn(1).setResizable(false);
            tMensagem.getColumnModel().getColumn(1).setPreferredWidth(50);
            tMensagem.getColumnModel().getColumn(2).setResizable(false);
            tMensagem.getColumnModel().getColumn(2).setPreferredWidth(70);
            tMensagem.getColumnModel().getColumn(3).setResizable(false);
            tMensagem.getColumnModel().getColumn(3).setPreferredWidth(140);
            tMensagem.getColumnModel().getColumn(4).setResizable(false);
            tMensagem.getColumnModel().getColumn(4).setPreferredWidth(5);
        }

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Bem Vindo");

        tNome.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        tNome.setText("NOME");

        bSair.setBackground(new java.awt.Color(255, 51, 51));
        bSair.setText("Sair");
        bSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSairActionPerformed(evt);
            }
        });

        jLabel2.setText("Filtro");

        bOk.setText("Ok");
        bOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOkActionPerformed(evt);
            }
        });

        tLer.setBackground(new java.awt.Color(30, 170, 239));
        tLer.setText("Ler");
        tLer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tLerActionPerformed(evt);
            }
        });

        jMenu1.setText("Opções");

        mNovo.setText("Nova Mensagem");
        mNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mNovoActionPerformed(evt);
            }
        });
        jMenu1.add(mNovo);

        mExcluir.setText("Excluir Mensagem");
        mExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mExcluirActionPerformed(evt);
            }
        });
        jMenu1.add(mExcluir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tNome, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tLer)
                        .addGap(18, 18, 18)
                        .addComponent(bSair))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bOk)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(bOk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tNome)
                    .addComponent(bSair)
                    .addComponent(tLer))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOkActionPerformed
        mensagemToTela();
    }//GEN-LAST:event_bOkActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        mensagemToTela();
    }//GEN-LAST:event_formWindowGainedFocus

    private void tLerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tLerActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tMensagem.getModel();
        if (tMensagem.getSelectedRow() != -1) {
            int id = (Integer) modelo.getValueAt(tMensagem.getSelectedRow(), 0);
            TelaVerMensagem tvm = new TelaVerMensagem();
            tvm.setMensagem(md.localiza(id));
            tvm.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Não há nada selecionado!");
        }
    }//GEN-LAST:event_tLerActionPerformed

    private void mNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mNovoActionPerformed
        TelaMensagem tm = new TelaMensagem();
        tm.setUsuario(ud.localiza(u.getUsuario()));
        tm.setVisible(true);
    }//GEN-LAST:event_mNovoActionPerformed

    private void bSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_bSairActionPerformed

    private void mExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mExcluirActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tMensagem.getModel();
        if (tMensagem.getSelectedRow() != -1) {
            int id = (Integer) modelo.getValueAt(tMensagem.getSelectedRow(), 0);
            Mensagem m = md.localiza(id);
            if (JOptionPane.showConfirmDialog(this, "Confirma exclusão da mensagem sobre  '" + m.getAssunto() + "'?") == JOptionPane.YES_OPTION) {
                md.excluiMensagem(m);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Não há nada selecionado!", "Selecione algo!", JOptionPane.PLAIN_MESSAGE, erroIcon2);
        }
    }//GEN-LAST:event_mExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLocalizaMensagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLocalizaMensagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLocalizaMensagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLocalizaMensagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLocalizaMensagem().setVisible(true);
            }
        });
    }

    public void setUsuario(Usuario u) {
        this.u = u;
        mensagemToTela();

    }

    private void mensagemToTela() {
        tNome.setText(u.getNome());
        DefaultTableModel modelo = (DefaultTableModel) tMensagem.getModel();
        int i = modelo.getRowCount();
        while (i-- > 0) {
            modelo.removeRow(i);
        }
        List<Mensagem> lista;
        if (tFiltro.getText().equals("")) {
            lista = md.pesquisa1(u.getUsuario());
        } else {
            lista = md.pesquisa(tFiltro.getText());
        }
        SimpleDateFormat s = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        //       Locale loc = new Locale("pt", "BR");
        //       DateFormat dateFormat = DateFormat.getDateInstance(DateFormat.DEFAULT, loc);
        for (Mensagem m : lista) {
            modelo.addRow(new Object[]{m.getId(), m.getRemetente(), m.getAssunto(), m.getMensagem(), s.format(m.getData().getTime())});
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bOk;
    private javax.swing.JButton bSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mExcluir;
    private javax.swing.JMenuItem mNovo;
    private javax.swing.JTextField tFiltro;
    private javax.swing.JButton tLer;
    private javax.swing.JTable tMensagem;
    private javax.swing.JLabel tNome;
    // End of variables declaration//GEN-END:variables
}
