/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import java.util.Date;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.Calendar;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import persistencia.AgricultorDAO;
import persistencia.EmprestimoDAO;
import persistencia.MaquinaDAO;
import vo.Emprestimo;

/**
 *
 * @author 2info2021
 */
public class TelaLocalizaEmprestimo extends javax.swing.JFrame {

    EmprestimoDAO ed = new EmprestimoDAO();
    Emprestimo e = new Emprestimo();
    AgricultorDAO ad = new AgricultorDAO();
    MaquinaDAO md = new MaquinaDAO();

    SimpleDateFormat s = new SimpleDateFormat("dd/MM/yyyy");

    /**
     * Creates new form TelaLocalizaEmprestimo
     */
    public TelaLocalizaEmprestimo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tLocalizaEmprestimo = new javax.swing.JTable();
        bVeratrasos = new javax.swing.JButton();
        bVerTodos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        bDevolve = new javax.swing.JMenu();
        bNovo = new javax.swing.JMenuItem();
        bDevolver = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Emprestimos");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        tLocalizaEmprestimo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Id Agricultor", "Agricultor", "Id Maquina", "Maquina", "Data de Emprestimo", "Data Prevista", "Data de Devolução", "Emprestado"
            }
        ));
        jScrollPane1.setViewportView(tLocalizaEmprestimo);

        bVeratrasos.setText("Ver Atrasos");
        bVeratrasos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVeratrasosActionPerformed(evt);
            }
        });

        bVerTodos.setText("Ver Todos");
        bVerTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVerTodosActionPerformed(evt);
            }
        });

        jLabel1.setText("Procurar por Maquina:");

        jLabel2.setText("Procurar por Agricultor:");

        jButton3.setText("Procurar");

        bDevolve.setText("Ações");

        bNovo.setText("Novo Emprestimo");
        bNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNovoActionPerformed(evt);
            }
        });
        bDevolve.add(bNovo);

        bDevolver.setText("Devolver Emprestimo");
        bDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDevolverActionPerformed(evt);
            }
        });
        bDevolve.add(bDevolver);

        jMenuBar1.add(bDevolve);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSpinner1)))
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bVeratrasos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bVerTodos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bVeratrasos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bVerTodos)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton3)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNovoActionPerformed
        TelaEmprestimo te = new TelaEmprestimo();
        te.setVisible(true);
    }//GEN-LAST:event_bNovoActionPerformed

    private void bDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDevolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bDevolverActionPerformed

    private void bVerTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVerTodosActionPerformed
        preencheTabelaEmprestimo();
    }//GEN-LAST:event_bVerTodosActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        preencheTabelaEmprestimo();
    }//GEN-LAST:event_formWindowGainedFocus

    private void bVeratrasosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVeratrasosActionPerformed
        preencheTabelaEmprestimoAtrasado();
    }//GEN-LAST:event_bVeratrasosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLocalizaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLocalizaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLocalizaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLocalizaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLocalizaEmprestimo().setVisible(true);
            }
        });
    }

    private void preencheTabelaEmprestimo() {
        DefaultTableModel modelo = (DefaultTableModel) tLocalizaEmprestimo.getModel();
        int i = modelo.getRowCount();
        while (i-- > 0) {
            modelo.removeRow(i);
        }
        List<Emprestimo> lista;
        lista = ed.pesquisa();
        for (Emprestimo e : lista) {
            modelo.addRow(new Object[]{e.getId(), e.getIdAgricultor(), ad.localiza(e.getIdAgricultor()).getNome(), e.getIdMaquina(), md.localiza(e.getIdMaquina()).getNome(), s.format(e.getDataEmprestimo()), s.format(e.getDataPrevista()), s.format(e.getDataDevolucao()), e.isEmprestado()});
        }
    }

    private void preencheTabelaEmprestimoAtrasado() {
        Date dataatual = new Date();
        DefaultTableModel modelo = (DefaultTableModel) tLocalizaEmprestimo.getModel();
        int i = modelo.getRowCount();
        while (i-- > 0) {
            modelo.removeRow(i);
        }
        List<Emprestimo> lista;
        lista = ed.pesquisaAtrasos(dataatual);
        for (Emprestimo e : lista) {
            modelo.addRow(new Object[]{e.getId(), e.getIdAgricultor(), ad.localiza(e.getIdAgricultor()).getNome(), e.getIdMaquina(), md.localiza(e.getIdMaquina()).getNome(), s.format(e.getDataEmprestimo()), s.format(e.getDataPrevista()), s.format(e.getDataDevolucao()), e.isEmprestado()});
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu bDevolve;
    private javax.swing.JMenuItem bDevolver;
    private javax.swing.JMenuItem bNovo;
    private javax.swing.JButton bVerTodos;
    private javax.swing.JButton bVeratrasos;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTable tLocalizaEmprestimo;
    // End of variables declaration//GEN-END:variables
}
