/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import java.text.DecimalFormat;
import javax.swing.ImageIcon;
import javax.swing.JSpinner;
import persistencia.FuncionarioDAO;
import vo.Funcionario;
import vo.Tabela;
import vo.CalculaFolha;

/**
 *
 * @author 2info2021
 */
public class TelaHolerite extends javax.swing.JFrame {

    Funcionario f = new Funcionario();
    FuncionarioDAO fd = new FuncionarioDAO();
    Tabela t = new Tabela();
    CalculaFolha cf = new CalculaFolha();
    double desconto;
    double vencimento;

    /**
     * Creates new form TelaHolerite
     */
    public TelaHolerite() {
        initComponents();
    }
    DecimalFormat numberFormat = new DecimalFormat("#0.00");

    private void funcionarioToTela() {

        cf.setTabela(fd.localizaTabela(1));
        cf.setFuncionario(fd.localiza(f.getMatricula()));
        cf.calcula();

        vencimento = cf.getSf() + f.getSalario();
        desconto = cf.getInss() + cf.getIrrf() + cf.getVt();
        tMatricula.setText(Integer.toString(f.getMatricula()));
        tNome2.setText(f.getNome());
        tSalario.setText(Double.toString(f.getSalario()));
        tSf.setText(numberFormat.format(cf.getSf()));
        tIrrf.setText(numberFormat.format(cf.getIrrf()));
        tInss.setText(numberFormat.format(cf.getInss()));
        tVt.setText(numberFormat.format(cf.getVt()));
        tSaliq.setText(numberFormat.format(cf.getSalliq()));
        tDesconto.setText(numberFormat.format(desconto));
        tVencimento.setText(numberFormat.format(vencimento));
    }

    public void setFuncionario(Funcionario f) {
        this.f = f;
        funcionarioToTela();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tMatricula = new javax.swing.JLabel();
        tNome = new javax.swing.JLabel();
        tSf = new javax.swing.JLabel();
        tIrrf = new javax.swing.JLabel();
        tInss = new javax.swing.JLabel();
        tSaliq = new javax.swing.JLabel();
        tSalario = new javax.swing.JLabel();
        tNome2 = new javax.swing.JLabel();
        tVt = new javax.swing.JLabel();
        tDesconto = new javax.swing.JLabel();
        tVencimento = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(739, 509));
        getContentPane().setLayout(null);
        getContentPane().add(tMatricula);
        tMatricula.setBounds(40, 80, 40, 20);
        getContentPane().add(tNome);
        tNome.setBounds(190, 80, 110, 0);

        tSf.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tSf.setText("drfg");
        getContentPane().add(tSf);
        tSf.setBounds(420, 150, 100, 14);

        tIrrf.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tIrrf.setText("drfg");
        getContentPane().add(tIrrf);
        tIrrf.setBounds(560, 170, 100, 14);

        tInss.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tInss.setText("drfg");
        getContentPane().add(tInss);
        tInss.setBounds(560, 190, 100, 15);

        tSaliq.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tSaliq.setText("drfg");
        getContentPane().add(tSaliq);
        tSaliq.setBounds(540, 420, 100, 15);

        tSalario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tSalario.setText("drfg");
        getContentPane().add(tSalario);
        tSalario.setBounds(420, 130, 100, 20);

        tNome2.setText("jLabel1");
        getContentPane().add(tNome2);
        tNome2.setBounds(190, 80, 110, 14);

        tVt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tVt.setText("drfg");
        getContentPane().add(tVt);
        tVt.setBounds(560, 210, 100, 15);

        tDesconto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tDesconto.setText("drfg");
        getContentPane().add(tDesconto);
        tDesconto.setBounds(560, 370, 100, 15);

        tVencimento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tVencimento.setText("drfg");
        getContentPane().add(tVencimento);
        tVencimento.setBounds(420, 370, 100, 15);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagem_fundo.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 0, 730, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaHolerite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaHolerite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaHolerite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaHolerite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaHolerite().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel tDesconto;
    private javax.swing.JLabel tInss;
    private javax.swing.JLabel tIrrf;
    private javax.swing.JLabel tMatricula;
    private javax.swing.JLabel tNome;
    private javax.swing.JLabel tNome2;
    private javax.swing.JLabel tSalario;
    private javax.swing.JLabel tSaliq;
    private javax.swing.JLabel tSf;
    private javax.swing.JLabel tVencimento;
    private javax.swing.JLabel tVt;
    // End of variables declaration//GEN-END:variables
}
